export const SET_DOCTOR_ORDER = 'SET_DOCTOR_ORDER';
export const SET_APPOINTMENT_DETAILS = 'SET_APPOINTMENT_DETAILS';
export const SET_CURRENT_FLOW = 'SET_CURRENT_FLOW';
export const SET_ID_IMAGE = 'SET_ID_IMAGE';